# __Introduction to NumPy__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

## __1. Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`.

## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [1]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [2]:
type(arr)

numpy.ndarray

### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [3]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)

0D array is 24


In [4]:
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)

1D array is [1 2 3 4]


In [5]:
# Create a 2D Array
arr2 = np.array([[1,1,1],
                 [1,2,1]])
print ('2D array is', arr2)

2D array is [[1 1 1]
 [1 2 1]]


In [6]:
arr2

array([[1, 1, 1],
       [1, 2, 1]])

In [7]:
# Create a 3D Array
arr3 = np.array([[[1,1,1],
                  [2,2,2]],
                 [[3,3,3],
                  [4,4,4]]])
print ('3D array is', arr3)

3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [8]:
arr3

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [9]:
print(arr0.shape) # scalar
print(arr1.shape) # 1D are also called vectors
print(arr2.shape) # 2D are also called matrices
print(arr3.shape) # 3D are also called tensors

()
(4,)
(2, 3)
(2, 2, 3)


**Observations:**
- 1D arrays are unidimensional and have 0D arrays as its elements.
- 2D arrays have 1D arrays as their elements.
- 3D arrays have 2D arrays as their elements.

## __Assisted Practice__

### __Problem Statement:__

Create the following NumPy arrays and print them using appropriate code:

- A 0D array (scalar)

- A 1D array with elements [1, 2, 3, 4]

- A 2D array with elements [[1, 1, 1], [1, 2, 1]]

- A 3D array with elements [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]

In [10]:
zero_arr = np.array(20)
zero_arr

array(20)

In [11]:
zero_arr.shape

()

In [12]:
# 1D array with elements [1, 2, 3, 4]
arr_1d = np.array([1, 2, 3, 4])
arr_1d

array([1, 2, 3, 4])

In [13]:
arr_1d.shape

(4,)

In [14]:
#  2D array with elements [[1, 1, 1], [1, 2, 1]]
arr_2d = np.array([[1, 1, 1], [1, 2, 1]])
arr_2d

array([[1, 1, 1],
       [1, 2, 1]])

In [15]:
arr_2d.shape

(2, 3)

In [16]:
# 3D array with elements [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
arr_3d = np.array([[[1, 1, 1], 
                    [2, 2, 2]], 
                   [[3, 3, 3], 
                    [4, 4, 4]]])
arr_3d

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [17]:
arr_3d.shape

(2, 2, 3)