# __NumPy Arithmetic Statistical and String Functions__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:
- Arithmetic Operations Using NumPy
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Power of
- Statistical Function in Numpy
  * Calculating Median, Mean, Standard Deviation, and Variance in the Array
  * Calculating Percentiles
- String Function in Numpy

## __1. Arithmetic Operations Using NumPy__ ##
### __1.1 Addition__ ###

In [1]:
# Perform element-wise addition of two arrays using the 'np.add' method
import numpy as np
a = np.array([30,20,10])
b = np.array([10,20,30])

In [2]:
a

array([30, 20, 10])

In [3]:
b

array([10, 20, 30])

In [4]:
a+b

array([40, 40, 40])

In [5]:
a

array([30, 20, 10])

In [6]:
result = np.add (a,b)
result

array([40, 40, 40])

### __1.2 Subtraction__ ###

In [7]:
# Perform element-wise subtraction of two arrays using 'np.subtract' method
a = np.array([[30,40,60], 
              [50,70,90]])

b = np.array([[10,20,30], 
              [40,30,80]])

result = np.subtract (a,b)
print(result)

[[20 20 30]
 [10 40 10]]


In [8]:
a-b

array([[20, 20, 30],
       [10, 40, 10]])

### __1.3 Multiplication__ ###

In [9]:
# Perform "element-wise multiplication" of two arrays using the 'np.multiply' method
a = np.array([30,20,10])
b = np.array([10,20,30])

result = np.multiply (a,b)
print(result)

[300 400 300]


In [10]:
a*b

array([300, 400, 300])

In [11]:
# matrix multiplication
np.matmul(a,b)

1000

### __1.4 Division__ ###

In [12]:
# Perform element-wise division of two arrays using the 'np.divide' method
a = np.array([[1,2,1],
              [2,2,3]])
print("Shape of matrix a: ", a.shape)

Shape of matrix a:  (2, 3)


In [13]:
b = np.array([3,4,5])
print("Shape of matrix b: ", b.shape)

Shape of matrix b:  (3,)


In [14]:
result = np.divide (a,b)
print(result)
print("Shape of matrix result: ", result.shape) # broadcasting

[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]
Shape of matrix result:  (2, 3)


### __1.5 Power of__ ###

In [15]:
# Perform element-wise power operation where each element in 'a' is raised to the corresponding element in 'b' using the 'np.power' method
a = [2,2,2,2,2]
b = [2,3,4,5,6]
a = np.array(a)
b = np.array(b)
c = np.power(a,b)
print(c)

[ 4  8 16 32 64]


## __2. Statistical Function in Numpy__ ##
### __2.1 Calculating Median, Mean, Standard Deviation, and Variance in the Array__ ###

In [16]:
# Median
array = np.array([[4,3,2],
                  [10,1,0],
                  [5,8,24]])
array

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [17]:
np.median(array) # median the 50th percentile. arrange from min to max and see which is the midpoint

4.0

In [18]:
# Mean
np.mean(array)

6.333333333333333

In [19]:
# Standard Deviation
np.std(array)

6.944222218666553

In [20]:
# Variance
np.var(array)

48.22222222222222

### __2.2 Calculating Percentiles__ ###
- The `np.percentile()` function is used to compute the nth percentile of the array elements.
- The nth percentile value should be in between 0 and 100.

In [22]:
# Find the value under the 30th percentile of the NumPy array.
np.percentile(array,50) # 50th percentile

4.0

In [23]:
np.mean(array)

6.333333333333333

In [24]:
array.mean() # mean method of array

6.333333333333333

In [25]:
np.max(array)

24

## __3. String Function in Numpy__ ##

In [26]:
# Perform element-wise string concatenation for two arrays of string
x = np.array(['Hello','World'])
y = np.array(['Welcome', 'Learners'])

In [27]:
x

array(['Hello', 'World'], dtype='<U5')

In [28]:
y

array(['Welcome', 'Learners'], dtype='<U8')

In [29]:
"Data" + " Science"

'Data Science'

In [30]:
result = np.char.add(x,y)
print(result) 

['HelloWelcome' 'WorldLearners']


In [34]:
# Replacing the old substring with the new substring
string = "Hello Hello How Are You"
print(string)

Hello Hello How Are You


In [35]:
z = np.char.replace (string, 'Hello', 'Hi')
print (z)

Hi Hi How Are You


In [36]:
# Converting all lowercase characters in a string to uppercase and vice-versa
str1 = "hello how are you"
print(str1)
z = np.char.upper (str1)
print(z)

hello how are you
HELLO HOW ARE YOU


In [37]:

str2 = "GREETINGS OF THE DAY"
print(str2)
s = np.char.lower (str2)
print(s)

GREETINGS OF THE DAY
greetings of the day


## __Assisted Practice__

### __Problem Statement:__

Consider the following arrays:

- Arrays for Arithmetic Operations:
  * Array A: [15, 25, 35, 45, 55]
  * Array B: [5, 10, 15, 20, 25]

In [39]:
A = np.array([15, 25, 35, 45, 55])
B = np.array([5, 10, 15, 20, 25])

- Array for Statistical Operations:
  * Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]

In [40]:
C = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])

- Arrays for String Functions:
  * String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
  * String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
  
  

In [41]:
X = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])

__Steps to Perform:__

1. Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B

In [42]:
# addition
np.add(A,B)

array([20, 35, 50, 65, 80])

In [43]:
# subtraction
np.subtract(A,B)

array([10, 15, 20, 25, 30])

In [44]:
# multiplication
np.multiply(A,B)

array([  75,  250,  525,  900, 1375])

In [45]:
# division
np.divide(A,B) # A/B

array([3.        , 2.5       , 2.33333333, 2.25      , 2.2       ])

In [46]:
np.power(A,B)

array([             759375,      95367431640625, 3351328013648404811,
       6545036034076902481, 6038590913291571831])

2. Calculate the median, mean, standard deviation, and variance for Array C

In [47]:
# median of array C
np.median(C)

57.0

In [48]:
# mean of array C
np.mean(C)

57.0

In [49]:
# standard deviation of array C
np.std(C)

28.722813232690143

In [50]:
# variance of array C
np.var(C)

825.0

3. Concatenate corresponding elements of String Arrays X and Y

In [51]:
# concatenate the elements of X and Y
np.char.add(X,Y)

array(['HelloWorld', 'DataAnalysis', 'Scienceis', 'ClassFun',
       'Learners2023'], dtype='<U16')

4. Convert all elements in String Array X to uppercase

In [52]:
# convert elements in A to uppercase
np.char.upper(X)

array(['HELLO', 'DATA', 'SCIENCE', 'CLASS', 'LEARNERS'], dtype='<U8')

5. Replace a specific substring in String Array Y with another substring

In [53]:
# replace "Fun" with "Awesome" in Y
np.char.replace(Y, 'Fun', 'Awesome')

array(['World', 'Analysis', 'is', 'Awesome', '2023'], dtype='<U8')